### ISSUE TITLE
Deploying the project

### ISSUE THREAD

**Issue by sauhards** [ndc07/hotel-management#2]
Can you please give me instructions on how to make this project work. I am new to this technology and the description which you gave in README was difficult for me to understand.

**Comment by cuongtk8** [comment]
@tvc12

**Comment by cuongtk8** [comment]
Please upgrade to [hotel-management-v2](https://github.com/uiters/hotel-management-v2).
We created a setup file, at [here](https://github.com/uiters/hotel-management-v2/blob/master/Setup/setup.exe).
Hope you enjoy, @sauhards.
